//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Lowercase Letters.
        /// </summary>
        internal static string GeneratePasswordIncludeLowercaseLetters {
            get {
                return ResourceManager.GetString("GeneratePasswordIncludeLowercaseLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Numbers.
        /// </summary>
        internal static string GeneratePasswordIncludeNumbers {
            get {
                return ResourceManager.GetString("GeneratePasswordIncludeNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Symbols.
        /// </summary>
        internal static string GeneratePasswordIncludeSymbols {
            get {
                return ResourceManager.GetString("GeneratePasswordIncludeSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Uppercase Letters.
        /// </summary>
        internal static string GeneratePasswordIncludeUppercaseLetters {
            get {
                return ResourceManager.GetString("GeneratePasswordIncludeUppercaseLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password length.
        /// </summary>
        internal static string GeneratePasswordLength {
            get {
                return ResourceManager.GetString("GeneratePasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password generator.
        /// </summary>
        internal static string GeneratePasswordTitle {
            get {
                return ResourceManager.GetString("GeneratePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string PasswordsDeleteButton {
            get {
                return ResourceManager.GetString("PasswordsDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordsPasswordTextBoxHint {
            get {
                return ResourceManager.GetString("PasswordsPasswordTextBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords.
        /// </summary>
        internal static string PasswordsTitle {
            get {
                return ResourceManager.GetString("PasswordsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string PasswordsUserTextBoxHint {
            get {
                return ResourceManager.GetString("PasswordsUserTextBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string PasswordsWebsiteTextBoxHint {
            get {
                return ResourceManager.GetString("PasswordsWebsiteTextBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply cahnges.
        /// </summary>
        internal static string ProfileApplyChangesButton {
            get {
                return ResourceManager.GetString("ProfileApplyChangesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string ProfileChangePasswordTextBox {
            get {
                return ResourceManager.GetString("ProfileChangePasswordTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string ProfileConfirmPasswordTextBoxHint {
            get {
                return ResourceManager.GetString("ProfileConfirmPasswordTextBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        internal static string ProfileCurrentPasswordTextBoxHint {
            get {
                return ResourceManager.GetString("ProfileCurrentPasswordTextBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ProfileNameTextBoxHint {
            get {
                return ResourceManager.GetString("ProfileNameTextBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string ProfileNewPasswordTextBoxHint {
            get {
                return ResourceManager.GetString("ProfileNewPasswordTextBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal infromation.
        /// </summary>
        internal static string ProfilePersonalInformationTextBox {
            get {
                return ResourceManager.GetString("ProfilePersonalInformationTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        internal static string ProfileSurnameTextBoxHint {
            get {
                return ResourceManager.GetString("ProfileSurnameTextBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal data.
        /// </summary>
        internal static string ProfileTitle {
            get {
                return ResourceManager.GetString("ProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string ProfileUsernameTextBoxHint {
            get {
                return ResourceManager.GetString("ProfileUsernameTextBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Appearance.
        /// </summary>
        internal static string SettingsAppearanceTextBlock {
            get {
                return ResourceManager.GetString("SettingsAppearanceTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoclear buffer.
        /// </summary>
        internal static string SettingsAutoclearBufferCheckbox {
            get {
                return ResourceManager.GetString("SettingsAutoclearBufferCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable 2FA.
        /// </summary>
        internal static string SettingsEnable2FACheckBox {
            get {
                return ResourceManager.GetString("SettingsEnable2FACheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable auto lock after.
        /// </summary>
        internal static string SettingsEnableAutoLockAfter {
            get {
                return ResourceManager.GetString("SettingsEnableAutoLockAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string SettingsLanguageComboBox {
            get {
                return ResourceManager.GetString("SettingsLanguageComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Safety.
        /// </summary>
        internal static string SettingsSafetyTextBox {
            get {
                return ResourceManager.GetString("SettingsSafetyTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string SettingsThemeComboBox {
            get {
                return ResourceManager.GetString("SettingsThemeComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        internal static string TabControlFavorites {
            get {
                return ResourceManager.GetString("TabControlFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Generator.
        /// </summary>
        internal static string TabControlPasswordGenerator {
            get {
                return ResourceManager.GetString("TabControlPasswordGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords.
        /// </summary>
        internal static string TabControlPasswords {
            get {
                return ResourceManager.GetString("TabControlPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string TabControlProfile {
            get {
                return ResourceManager.GetString("TabControlProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string TabControlSettings {
            get {
                return ResourceManager.GetString("TabControlSettings", resourceCulture);
            }
        }
    }
}
