//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string PasswordsDeleteButton {
            get {
                return ResourceManager.GetString("PasswordsDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordsPasswordTextBoxHint {
            get {
                return ResourceManager.GetString("PasswordsPasswordTextBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords.
        /// </summary>
        public static string PasswordsTitle {
            get {
                return ResourceManager.GetString("PasswordsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string PasswordsUserTextBoxHint {
            get {
                return ResourceManager.GetString("PasswordsUserTextBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string PasswordsWebsiteTextBoxHint {
            get {
                return ResourceManager.GetString("PasswordsWebsiteTextBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply cahnges.
        /// </summary>
        public static string ProfileApplyChangesButton {
            get {
                return ResourceManager.GetString("ProfileApplyChangesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ProfileChangePasswordTextBox {
            get {
                return ResourceManager.GetString("ProfileChangePasswordTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ProfileConfirmPasswordTextBoxHint {
            get {
                return ResourceManager.GetString("ProfileConfirmPasswordTextBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string ProfileCurrentPasswordTextBoxHint {
            get {
                return ResourceManager.GetString("ProfileCurrentPasswordTextBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ProfileNameTextBoxHint {
            get {
                return ResourceManager.GetString("ProfileNameTextBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string ProfileNewPasswordTextBoxHint {
            get {
                return ResourceManager.GetString("ProfileNewPasswordTextBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal infromation.
        /// </summary>
        public static string ProfilePersonalInformationTextBox {
            get {
                return ResourceManager.GetString("ProfilePersonalInformationTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string ProfileSurnameTextBoxHint {
            get {
                return ResourceManager.GetString("ProfileSurnameTextBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal data.
        /// </summary>
        public static string ProfileTitle {
            get {
                return ResourceManager.GetString("ProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string ProfileUsernameTextBoxHint {
            get {
                return ResourceManager.GetString("ProfileUsernameTextBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string TabControlFavorites {
            get {
                return ResourceManager.GetString("TabControlFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasswordGenerator.
        /// </summary>
        public static string TabControlPasswordGenerator {
            get {
                return ResourceManager.GetString("TabControlPasswordGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords.
        /// </summary>
        public static string TabControlPasswords {
            get {
                return ResourceManager.GetString("TabControlPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string TabControlProfile {
            get {
                return ResourceManager.GetString("TabControlProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string TabControlSettings {
            get {
                return ResourceManager.GetString("TabControlSettings", resourceCulture);
            }
        }
    }
}
